const {app,BrowserWindow,Menu,Tray,ipcMain,shell,dialog,nativeImage}=require('electron');
const {join}=require('node:path');const {pathToFileURL}=require('node:url');const {readFile,writeFile,mkdir}=require('node:fs/promises');const {spawn}=require('node:child_process');
const media=require('./media.cjs');
const {normalizeAddress,sameOrigin,externalLink}=require('./policy.cjs');
let launcher,library,tray,child,quitting=false,currentOrigin='',localOrigin='',ownsService=false;
const launcherFile=join(__dirname,'launcher/index.html'),launcherUrl=pathToFileURL(launcherFile).href;
if(process.env.ZNOTE_DESKTOP_TEST_DATA)app.setPath('userData',process.env.ZNOTE_DESKTOP_TEST_DATA);
const reveal=win=>{if(process.env.ZNOTE_DESKTOP_HEADLESS!=='1')win?.show()};
const appData=()=>process.env.ZNOTE_DESKTOP_TEST_DATA||app.getPath('userData');
const configPath=()=>join(appData(),'connection.json');
async function config(){try{return JSON.parse(await readFile(configPath(),'utf8'))}catch{return {}}}
async function health(origin){const response=await fetch(origin+'/api/health',{signal:AbortSignal.timeout(5000),redirect:'error'});if(!response.ok)throw Error('服务器未正常响应');const raw=await response.text();if(raw.length>2048)throw Error('服务器返回异常');const data=JSON.parse(raw);if(data.status!=='ok'||typeof data.version!=='string')throw Error('该地址不是可用的 ZNote 服务');return data;}
function secure(win,origin){win.webContents.session.setPermissionRequestHandler((_w,_p,done)=>done(false));win.webContents.session.setPermissionCheckHandler(()=>false);win.webContents.setWindowOpenHandler(({url})=>{if(externalLink(url))shell.openExternal(url);return {action:'deny'}});win.webContents.on('will-navigate',(e,url)=>{if(!sameOrigin(url,origin)){e.preventDefault();if(externalLink(url))shell.openExternal(url)}});win.webContents.on('will-attach-webview',e=>e.preventDefault());}
function feedback(){return shell.openExternal('https://github.com/BorderArea01/ZNote/issues/new/choose')}
function showLauncher(){if(!launcher||launcher.isDestroyed()){launcher=new BrowserWindow({title:'ZNote · 连接知识库',width:660,height:810,minWidth:460,minHeight:620,backgroundColor:'#121622',show:false,webPreferences:{preload:join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true}});launcher.webContents.setWindowOpenHandler(()=>({action:'deny'}));launcher.webContents.on('will-navigate',e=>e.preventDefault());launcher.loadFile(launcherFile);launcher.once('ready-to-show',()=>reveal(launcher));launcher.on('closed',()=>{launcher=null})}else{reveal(launcher);launcher.focus()}}
function menu(){const entries=[{label:'打开知识库',click:()=>{if(library&&!library.isDestroyed()){reveal(library);library.focus()}else showLauncher()}},{label:'连接其他知识库',click:showLauncher},{label:'在浏览器打开',enabled:!!currentOrigin,click:()=>shell.openExternal(currentOrigin)},{label:'本机数据目录',enabled:ownsService,click:()=>shell.openPath(join(appData(),'data'))},{type:'separator'},{label:'反馈与帮助',click:feedback},{label:'退出 ZNote',click:()=>app.quit()}];tray?.setContextMenu(Menu.buildFromTemplate(entries));Menu.setApplicationMenu(Menu.buildFromTemplate([...(process.platform==='darwin'?[{role:'appMenu'}]:[]),{label:'知识库',submenu:entries},{role:'editMenu'},{role:'viewMenu'}]));}
async function openLibrary(origin){await health(origin);if(library&&!library.isDestroyed()){const choice=await dialog.showMessageBox(library,{type:'question',buttons:['取消','切换知识库'],defaultId:0,cancelId:0,message:'切换连接前，请先保存当前编辑。'});if(choice.response!==1)return;library.destroy();}currentOrigin=origin;library=new BrowserWindow({title:'ZNote',width:1440,height:960,minWidth:780,minHeight:600,backgroundColor:'#151923',show:false,webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true,webSecurity:true}});secure(library,origin);library.on('close',e=>{if(!quitting&&tray){e.preventDefault();library.hide();}});library.once('ready-to-show',()=>{reveal(library);launcher?.hide()});library.webContents.on('did-fail-load',(_e,code,_description,_url,isMainFrame)=>{if(isMainFrame&&code!==-3){showLauncher();}});await library.loadURL(origin);await mkdir(appData(),{recursive:true});await writeFile(configPath(),JSON.stringify({address:origin},null,2));menu();}
async function startLocal(){if(localOrigin){await health(localOrigin);return localOrigin;}const defaultOrigin='http://127.0.0.1:3741';if(!process.env.ZNOTE_DESKTOP_TEST_DATA){try{await health(defaultOrigin);return defaultOrigin}catch{}}
 const root=app.isPackaged?join(process.resourcesPath,'runtime'):join(__dirname,'runtime'),node=join(root,process.platform==='win32'?'node.exe':'node'),dataDir=join(appData(),'data');await mkdir(dataDir,{recursive:true});
 const mediaPaths=media.paths(appData());const mediaEnv=(await media.installed(appData()))?{ZNOTE_YTDLP:mediaPaths.downloader,ZNOTE_FFMPEG:mediaPaths.ffmpeg}:{};
 const ready=new Promise((resolve,reject)=>{child=spawn(node,[join(root,'app','desktop-service.mjs')],{cwd:join(root,'app'),windowsHide:true,stdio:['ignore','ignore','pipe','ipc'],env:{...process.env,...mediaEnv,NODE_ENV:'production',DATA_DIR:dataDir,PORT:process.env.ZNOTE_DESKTOP_TEST_DATA?'0':'3741',HOST:'0.0.0.0'}});let settled=false;const timer=setTimeout(()=>{if(!settled){settled=true;child.kill();reject(Error('本机服务启动超时，请检查存储空间与端口占用'))}},20000);child.stderr.on('data',()=>{});child.once('error',()=>{clearTimeout(timer);if(!settled){settled=true;reject(Error('内置运行环境无法启动，请重新安装对应系统的客户端'))}});child.on('message',value=>{if(settled)return;if(value?.type==='ready'){settled=true;clearTimeout(timer);ownsService=true;localOrigin='http://127.0.0.1:'+value.port;resolve(localOrigin);}else if(value?.type==='error'){settled=true;clearTimeout(timer);reject(Error(value.code==='EADDRINUSE'?'3741 端口被其他程序占用，请连接已有服务或释放端口':'本机知识库无法启动，请检查数据目录与运行环境'));}});child.once('exit',()=>{clearTimeout(timer);localOrigin='';ownsService=false;child=null;if(!settled){settled=true;reject(Error('本机服务已停止，未能完成启动'))}else if(!quitting){menu();showLauncher();dialog.showErrorBox('ZNote 服务已停止','本机服务意外退出，已保留数据。请重新打开本机知识库。')}});});return ready;}
function handle(name,fn){ipcMain.handle(name,async(event,...args)=>{if(event.senderFrame?.url!==launcherUrl||event.sender!==launcher?.webContents)throw Error('Invalid sender');try{return await fn(...args)}catch(e){return {error:e.message||'操作失败'}}})}
if(!app.requestSingleInstanceLock()){app.quit()}else{
 app.on('second-instance',()=>{if(library&&!library.isDestroyed()){reveal(library);library.focus()}else showLauncher()});
 app.whenReady().then(async()=>{app.setAppUserModelId('io.github.borderarea01.znote');handle('launcher:state',async()=>({address:(await config()).address||'',version:app.getVersion()}));handle('launcher:connect',async value=>{await openLibrary(normalizeAddress(value));return {ok:true}});handle('launcher:local',async()=>{await openLibrary(await startLocal());return {ok:true}});handle('launcher:media',async()=>{if(ownsService)return {error:'请先从托盘退出 ZNote，重新打开后安装组件，再启动本机库。'};await media.install(appData());return {message:'视频组件已安装，打开本机知识库即可使用。'}});handle('launcher:feedback',feedback);
  const icon=nativeImage.createFromPath(join(__dirname,'launcher/icon.png'));if(!icon.isEmpty()){tray=new Tray(icon.resize({width:20,height:20}));tray.setToolTip('ZNote · 关闭窗口后继续收件');tray.on('double-click',()=>{if(library&&!library.isDestroyed())reveal(library);else showLauncher()})}menu();showLauncher();
 });
 app.on('activate',()=>{if(library&&!library.isDestroyed())reveal(library);else showLauncher()});app.on('window-all-closed',()=>{if(!tray)app.quit()});
 app.on('before-quit',event=>{if(quitting)return;quitting=true;if(child){event.preventDefault();const process=child;process.once('exit',()=>app.quit());if(process.connected)process.send({type:'stop'},()=>{});else process.kill();setTimeout(()=>{if(child)child.kill();app.quit()},15000).unref();}});
}
