import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {mkdtemp,readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
import sharp from 'sharp';
const dir=await mkdtemp(resolve('artifacts/blacklist-')),png=await sharp({create:{width:900,height:600,channels:3,background:'#8282bb'}}).png().toBuffer(),mp4=await readFile('tests/fixtures/sample.mp4');
const server=createServer((req,res)=>{if(req.url.startsWith('/image.png')){res.setHeader('Content-Type','image/png');return res.end(png)}if(req.url.startsWith('/video.mp4')){res.setHeader('Content-Type','video/mp4');return res.end(mp4)}res.setHeader('Content-Type','text/html');res.end(`<!doctype html><html><head>${req.url==='/library'?'<meta name="znote-app" content="knowledge-base">':''}</head><body><h1>Media fixture</h1><img width="300" src="/image.png"><video width="300" src="/video.mp4" controls></video></body></html>`)});server.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
const extension=resolve('addons/browser/clipper'),context=await chromium.launchPersistentContext(dir,{channel:'msedge',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`],viewport:{width:1400,height:1000}});
try{
 const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),origin='chrome-extension://'+new URL(worker.url()).host,page=await context.newPage();await page.goto(base);const overlay=page.locator('[data-znote-overlay]'),dock=overlay.locator('.dock');await dock.waitFor();await page.locator('body>img').hover();await overlay.locator('.preview:not(.hidden)').waitFor();await page.mouse.move(900,900);await dock.click();await overlay.locator('.item').first().waitFor();
 await page.evaluate(async()=>{await fetch('/image.png?sniff=1');await fetch('/video.mp4?sniff=1')});await page.waitForTimeout(600);let state=await worker.evaluate(()=>chrome.storage.session.get('sniffTabs'));assert.ok(Object.values(state.sniffTabs).some(s=>s.resources.some(r=>r.kind==='image')&&s.resources.some(r=>r.kind==='video')));
 const options=await context.newPage();await options.goto(origin+'/options.html');await options.locator('#blocked-sites').fill(base);await options.locator('#behavior button[type=submit]').click();await options.locator('#status').filter({hasText:'已保存'}).waitFor();await dock.waitFor({state:'hidden'});await page.locator('body>img').hover();await page.waitForTimeout(400);assert.ok(await overlay.locator('.preview').isHidden());await page.evaluate(()=>fetch('/video.mp4?blocked=1'));await page.waitForTimeout(300);state=await worker.evaluate(()=>chrome.storage.session.get('sniffTabs'));assert.ok(Object.values(state.sniffTabs).every(s=>!s.enabled&&!s.resources.length),'blacklist clears captured media and stops both types');
 await options.locator('#blocked-sites').fill('');await options.locator('#behavior button[type=submit]').click();await dock.waitFor();await dock.click();await overlay.locator('.item').first().waitFor();console.log('PASS live blacklist activation and removal, image hover and image/video network capture');
 await page.goto(base+'/library');await page.locator('[data-znote-overlay]').waitFor({state:'attached'});await page.waitForTimeout(500);assert.ok(await page.locator('[data-znote-overlay] .dock').isHidden());await page.locator('body>img').hover();await page.waitForTimeout(350);assert.ok(await page.locator('[data-znote-overlay] .preview').isHidden());
 await worker.evaluate(server=>chrome.storage.local.set({server}),base);await page.goto(base);await page.waitForTimeout(500);assert.ok(await page.locator('[data-znote-overlay] .dock').isHidden());await options.screenshot({path:resolve('artifacts/v093-blacklist-options.png'),fullPage:true});console.log('PASS ZNote page marker and connected server auto-exclusion, settings retained');
}finally{await context.close();await new Promise(r=>server.close(r))}
