import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {mkdtemp,readFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import assert from 'node:assert/strict';
import {createApp} from '../server/app.js';
const dir=await mkdtemp(resolve('artifacts/douyin-save-')),runtime=createApp({dataDir:join(dir,'data')}),server=runtime.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port,bytes=await readFile('tests/fixtures/sample.mp4');
const source=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'video/mp4','Content-Length':bytes.length,'Access-Control-Allow-Origin':'*'});res.end(bytes)}).listen(0,'127.0.0.1');await new Promise(r=>source.once('listening',r));const videoUrl='http://127.0.0.1:'+source.address().port+'/movie.mp4';
const extension=resolve('addons/browser/clipper'),context=await chromium.launchPersistentContext(join(dir,'profile'),{channel:'msedge',headless:true,args:['--disable-extensions-except='+extension,'--load-extension='+extension]}),worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),page=await context.newPage();
try{
 const post=async(path,data)=>{const r=await context.request.post(base+path,{data});assert.ok(r.ok(),await r.text());return r.json()};await post('/api/auth/setup',{password:'0911'});const token=await post('/api/tokens',{name:'采集测试',scope:'write'}),library=await post('/api/collections',{name:'抖音视频'});
 await worker.evaluate(config=>chrome.storage.local.set(config),{server:base,token:token.token,collection_id:library.id,tags:'参考'});
 await page.route('https://www.douyin.com/**',route=>route.fulfill({contentType:'text/html; charset=utf-8',body:'<!doctype html><title>抖音</title><nav><a href="/user/self">我的账号</a></nav><main><section data-e2e="feed-video" data-aweme-id="123"><div data-e2e="video-desc">雨后的街道</div><video controls muted style="width:480px;height:320px" src="'+videoUrl+'"></video><div id="late"></div><div data-e2e="comment-list"><a href="/user/comment">评论路人</a></div></section></main>'}));
 await page.goto('https://www.douyin.com/user/self?modal_id=123&showTab=favorite_collection');const overlay=page.locator('[data-znote-overlay]');await overlay.getByRole('button',{name:'ZNote 视频嗅探',exact:true}).click();await overlay.locator('.panel .item').waitFor();await page.locator('#late').evaluate(el=>el.innerHTML='<a data-e2e="video-author-name" href="/user/real-author">@街头摄影师</a>');await overlay.getByRole('button',{name:'扫描',exact:true}).click();const row=overlay.locator('.panel .item').filter({hasText:'作者：街头摄影师'});await row.waitFor();
 const pagesBefore=context.pages().length;await row.getByRole('button',{name:'保存知识库',exact:true}).click();await row.getByText('已保存到知识库',{exact:true}).waitFor({timeout:30000});assert.equal(context.pages().length,pagesBefore);let list=await (await context.request.get(base+'/api/items?kind=video&collection='+library.id)).json();assert.equal(list.total,1);const saved=list.items[0];assert.equal(saved.title,'雨后的街道');assert.ok(saved.tags.includes('街头摄影师'));assert.ok(saved.tags.includes('抖音'));assert.ok(!saved.tags.includes('评论路人'));assert.ok(!saved.tags.includes('我的账号'));assert.equal(saved.source_url,'https://www.douyin.com/video/123');assert.ok(saved.content.includes('/user/real-author'));assert.ok((await (await context.request.get(base+saved.url)).body()).equals(bytes));
 // A previously saved video missing the tag gets enriched on re-save, without duplicates or note loss.
 await context.request.patch(base+'/api/items/'+saved.id,{data:{version:saved.version,tags:['手动标签'],content:'手写说明'}});await row.getByRole('button',{name:'保存知识库',exact:true}).click();await row.getByText('知识库已收录，已补充来源',{exact:true}).waitFor({timeout:30000});list=await (await context.request.get(base+'/api/items?kind=video&collection='+library.id)).json();assert.equal(list.total,1);assert.ok(list.items[0].tags.includes('街头摄影师'));assert.ok(list.items[0].tags.includes('手动标签'));assert.ok(list.items[0].content.includes('手写说明'));
 await page.screenshot({path:resolve('artifacts/v0911-douyin-author.png')});console.log('PASS actual Edge extension: late Douyin author -> no-tab background save -> author tag, source/profile links, original bytes and re-save enrichment');
}finally{await context.close();await runtime.trash.stop();await runtime.imports.stop();await runtime.backups.stop();await runtime.webhooks.stop();await new Promise(r=>server.close(r));await new Promise(r=>source.close(r));runtime.db.close()}
