import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import sharp from 'sharp';
import {createApp} from '../server/app.js';
test('group selection includes all members and bulk operations stay atomic above 100 images',async t=>{
 const dir=await mkdtemp(resolve('artifacts/group-selection-api-')),runtime=createApp({dataDir:dir}),server=runtime.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{await runtime.trash.stop();await runtime.imports.stop();await runtime.backups.stop();await runtime.webhooks.stop();await new Promise(r=>server.close(r));runtime.db.close()});
 const base='http://127.0.0.1:'+server.address().port,setup=await fetch(base+'/api/auth/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:'0910'})}),cookie=setup.headers.get('set-cookie').split(';')[0];
 const request=(path,method='GET',body)=>fetch(base+path,{method,headers:{Cookie:cookie,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}),json=async(...args)=>{const r=await request(...args);assert.ok(r.ok,await r.clone().text());return r.json()};
 const a=await json('/api/collections','POST',{name:'A'}),b=await json('/api/collections','POST',{name:'B'}),data=new FormData();data.set('file',new Blob([await sharp({create:{width:16,height:16,channels:3,background:'#987abc'}}).png().toBuffer()]),'test.png');data.set('collection_id',a.id);data.set('group_key','test:book');data.set('group_index','0');const r=await fetch(base+'/api/assets',{method:'POST',headers:{Cookie:cookie},body:data});assert.ok(r.ok);const first=await r.json(),source=runtime.db.prepare('SELECT * FROM items WHERE id=?').get(first.id);
 for(let i=1;i<126;i++){const row={...source,id:randomUUID(),group_index:i,collection_id:i===125?b.id:a.id},columns=Object.keys(row);runtime.db.prepare('INSERT INTO items('+columns.join(',')+') VALUES('+columns.map(()=>'?').join(',')+')').run(...columns.map(c=>row[c]))}
 const getSelection=()=>json('/api/item-groups/selection?id='+first.id);let selected=await getSelection();assert.equal(selected.items.length,125);assert.equal(selected.collection_id,a.id);assert.equal(selected.trash,false);assert.ok(selected.items.every(row=>row.favorite===false));
 const before=runtime.db.prepare('SELECT * FROM items ORDER BY id').all();let bad=selected.items.map(p=>({...p}));bad.at(-1).version++;assert.equal((await request('/api/items/batch-tags','POST',{items:bad,tags:['new']})).status,409);assert.deepEqual(runtime.db.prepare('SELECT * FROM items ORDER BY id').all(),before);
 await json('/api/items/batch-tags','POST',{items:selected.items,tags:['whole']});selected=await getSelection();assert.ok(runtime.db.prepare('SELECT tags FROM items WHERE collection_id=?').all(a.id).every(p=>JSON.parse(p.tags).includes('whole')));assert.equal(runtime.db.prepare('SELECT tags FROM items WHERE collection_id=?').get(b.id).tags,'[]');
 await json('/api/items/batch-trash','POST',{collection_id:a.id,items:selected.items});selected=await getSelection();assert.equal(selected.trash,true);assert.equal(selected.items.length,125);await json('/api/items/batch-trash','POST',{collection_id:a.id,items:selected.items,restore:true});
 const note=await json('/api/items','POST',{title:'整组笔记',collection_id:a.id,content:`![配图](${first.url})`});const pages=await json('/api/item-groups/selection?id='+note.id);await json('/api/items/batch-organize','POST',{items:pages.items,collection_id:b.id});assert.equal((await json('/api/items/'+note.id)).collection_id,b.id);assert.equal((await json('/api/items/'+pages.items[0].id)).collection_id,b.id);
 selected=await getSelection();await json('/api/items/batch-trash','POST',{collection_id:a.id,items:selected.items});const scope={collection_id:a.id,ids:selected.items.map(p=>p.id)},preview=await json('/api/trash/preview','POST',scope);assert.equal(preview.count,125);await json('/api/trash/purge','POST',{...scope,revision:preview.revision,confirm:'DELETE'});assert.equal((await request('/api/items/'+first.id)).status,404);assert.ok((await request('/media/'+pages.items[0].id+'/original')).ok);
});
