import {chromium} from 'playwright';
import {mkdtemp} from 'node:fs/promises';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {createApp} from '../server/app.js';
const dir=await mkdtemp(resolve('artifacts/interactions-')),runtime=createApp({dataDir:dir,staticDir:resolve(process.env.UI_DIST||'dist')}),server=runtime.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const post=async(path,data)=>{const r=await context.request.post(base+path,{data});assert.ok(r.ok(),await r.text());return r.json()};
const backdrop=async(dialog)=>{const shade=dialog.locator('..');await shade.click({position:{x:8,y:8}})};
try{
 await post('/api/auth/setup',{password:'0944'});const collection=await post('/api/collections',{name:'交互示例'}),pages=[];
 for(let i=0;i<3;i++){const buffer=await sharp({create:{width:1000,height:700,channels:3,background:['#8499bc','#bfa8a0','#98b1a0'][i]}}).png().toBuffer();const r=await context.request.post(base+'/api/assets',{multipart:{file:{name:'image.png',mimeType:'image/png',buffer},title:'图片 '+(i+1),collection_id:collection.id}});assert.ok(r.ok());pages.push(await r.json())}
 const note=await post('/api/items',{title:'图片引用示例',collection_id:collection.id,content:`这张图片的原文件保留在本地。\n\n![配图](${pages[0].url})`});
 // A soft-deleted note image must remain readable, not merely survive in the browser cache.
 const original=Buffer.from(await (await context.request.get(base+pages[0].url)).body());assert.equal((await context.request.delete(base+'/api/items/'+pages[0].id)).status(),204);
 assert.ok((await context.request.get(base+pages[0].url+'?uncached=1')).ok());assert.ok(Buffer.from(await (await context.request.get(base+pages[0].url)).body()).equals(original));
 await context.request.patch(base+'/api/preferences',{data:{default_collection_id:collection.id}});await page.goto(base);
 await page.getByRole('button',{name:'打开 图片引用示例',exact:true}).click();let noteDialog=page.getByRole('dialog',{name:'图文笔记',exact:true});await noteDialog.locator('.markdown-preview img').evaluate(img=>img.decode());assert.equal(await noteDialog.locator('.markdown-preview img').evaluate(img=>img.naturalWidth),1000);
 await noteDialog.locator('.markdown-preview img').click();const gallery=page.getByRole('dialog',{name:'笔记配图',exact:true});await gallery.getByRole('button',{name:'展开笔记配图'}).click();const zoom=page.getByRole('dialog',{name:'展开图片',exact:true});await zoom.locator('img').evaluate(img=>img.decode());await page.mouse.click(12,120);await zoom.waitFor({state:'hidden'});assert.ok(await gallery.isVisible());assert.ok(await noteDialog.isVisible());await backdrop(gallery);await gallery.waitFor({state:'hidden'});assert.ok(await noteDialog.isVisible());await page.keyboard.press('Escape');await noteDialog.waitFor({state:'hidden'});
 await page.getByRole('button',{name:'打开 图片 2',exact:true}).click();let detail=page.getByRole('dialog',{name:'图片详情',exact:true});await detail.locator('.dialog-header h2').click();assert.ok(await detail.isVisible());
 const rect=await detail.locator('#item-title').boundingBox();await page.mouse.move(rect.x+25,rect.y+20);await page.mouse.down();await page.mouse.move(8,8,{steps:6});await page.mouse.up();assert.ok(await detail.isVisible(),'dragging out of a dialog must not dismiss it');await backdrop(detail);await detail.waitFor({state:'hidden'});assert.equal(await page.getByRole('button',{name:'打开 图片 2',exact:true}).evaluate(el=>document.activeElement===el),true);
 await page.getByRole('button',{name:'打开 图片 2',exact:true}).click();await detail.locator('#item-title').fill('尚未保存的标题');page.once('dialog',dialog=>dialog.dismiss());await backdrop(detail);assert.ok(await detail.isVisible());assert.equal(await detail.locator('#item-title').inputValue(),'尚未保存的标题');page.once('dialog',dialog=>dialog.accept());await page.keyboard.press('Escape');await detail.waitFor({state:'hidden'});
 await page.getByRole('button',{name:'打开 图片 2',exact:true}).click();await detail.locator('#item-title').fill('保存后的图片');let release,entered;const held=new Promise(r=>release=r),arrived=new Promise(r=>entered=r);
 await page.route('**/api/items/*',async route=>{if(route.request().method()==='PATCH'){entered();await held;}await route.continue()});await detail.getByRole('button',{name:'保存',exact:true}).click();await arrived;await backdrop(detail);assert.ok(await detail.isVisible(),'saving must not be interrupted by backdrop dismissal');release();await page.unrouteAll({behavior:'wait'});await page.getByRole('status').filter({hasText:'已保存'}).waitFor();await page.keyboard.press('Escape');await detail.waitFor({state:'hidden'});
 await page.getByRole('button',{name:'选择内容',exact:true}).click();const first=page.getByRole('button',{name:'选择 保存后的图片',exact:true});await first.locator('img').click();assert.equal(await page.locator('.card-select input:checked').count(),1);assert.equal(await page.getByRole('dialog').count(),0);await page.getByRole('button',{name:'取消选择 保存后的图片',exact:true}).locator('.card-body h3').click();assert.equal(await page.locator('.card-select input:checked').count(),0);
 await page.getByRole('checkbox',{name:'选择 保存后的图片',exact:true}).check();assert.equal(await page.locator('.card-select input:checked').count(),1,'checkbox toggles once');const third=page.getByRole('button',{name:'选择 图片 3',exact:true});await third.focus();await page.keyboard.press('Space');assert.equal(await page.locator('.card-select input:checked').count(),2);
 await page.evaluate(()=>{document.documentElement.dataset.theme='dark';document.documentElement.dataset.palette='slate'});await page.waitForTimeout(250);await page.screenshot({path:resolve('artifacts/v094-selection-desktop.png')});
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'取消选择 图片 3',exact:true}).tap();assert.equal(await page.locator('.card-select input:checked').count(),1);await page.screenshot({path:resolve('artifacts/v094-selection-mobile.png')});await page.getByRole('button',{name:'退出选择',exact:true}).click();await page.getByRole('button',{name:'打开 图片 3',exact:true}).tap();await detail.waitFor();
 assert.deepEqual(errors,[]);console.log('PASS soft-deleted note image decoded uncached; nested/backdrop/Escape dismissal; drag and unsaved/busy guards; card/checkbox/keyboard/touch selection and normal preview');
}finally{await page.unrouteAll({behavior:'ignoreErrors'});await browser.close();await runtime.imports.stop();await runtime.backups.stop();await runtime.webhooks.stop();await new Promise(r=>server.close(r));runtime.db.close()}
