import { chromium } from 'playwright';
import { createApp } from '../server/app.js';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import assert from 'node:assert/strict';
import sharp from 'sharp';

const dir = await mkdtemp(resolve('artifacts/organize-ui-'));
const { app, db } = createApp({ dataDir: dir, staticDir: resolve('artifacts/build-v03') });
const server = app.listen(0, '127.0.0.1'); await new Promise(r => server.once('listening', r));
const base = `http://127.0.0.1:${server.address().port}`;
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
const post = async (path, data) => { const r = await context.request.post(base + path, { data }); assert.ok(r.ok(), await r.text()); return r.json(); };
try {
  await page.goto(base); await page.getByLabel('访问密码').fill('0063'); await page.getByRole('button', { name: '开始使用 ZNote' }).click();
  await page.getByRole('heading', { name: /我的知识库/ }).waitFor();
  const a = await post('/api/collections', { name: '图片研究' }), b = await post('/api/collections', { name: '共享参考' });
  await page.reload(); await page.getByRole('button', { name: '图片研究 0', exact: true }).click();
  const files = [];
  for (const [index, color] of ['#627a6c', '#748baf', '#b1916c'].entries()) {
    const file = join(dir, `研究素材${index + 1}.png`);
    await writeFile(file, await sharp({ create: { width: 1000, height: 750, channels: 3, background: color } }).png().toBuffer()); files.push(file);
  }
  await page.getByRole('button', { name: '上传图片', exact: true }).click();
  await page.getByRole('dialog').locator('input[type=file]').setInputFiles(files);
  await page.getByRole('button', { name: '开始上传', exact: true }).click();
  await page.getByRole('button', { name: '完成', exact: true }).waitFor();
  await page.getByRole('button', { name: '整理已上传图片' }).click();
  await page.getByLabel('标题', { exact: true }).fill('上传后直接整理');
  await page.getByRole('button', { name: '下一张 →' }).click();
  await page.waitForFunction(() => document.querySelector('#item-title')?.value === '研究素材2.png');
  let records = await (await context.request.get(base + '/api/items?collection=' + a.id)).json();
  assert.ok(records.items.some(i => i.title === '上传后直接整理'));
  await page.getByRole('dialog', { name: '图片详情' }).focus();
  await page.keyboard.press('f');
  await page.getByRole('button', { name: '取消收藏', exact: true }).waitFor();
  await page.getByRole('dialog', { name: '图片详情' }).focus();
  await page.keyboard.press('ArrowRight');
  await page.waitForFunction(() => document.querySelector('#item-title')?.value === '研究素材3.png');
  console.log('PASS: upload-to-gallery, autosave, stable order, arrow shortcuts and favorite');
  await page.getByRole('button', { name: '复用到其他知识库', exact: true }).click();
  const copy = page.getByRole('dialog', { name: '复用到其他知识库', exact: true });
  await copy.getByLabel('整理目标知识库').selectOption(b.id);
  await copy.getByRole('button', { name: '确认整理' }).click();
  await copy.waitFor({ state: 'hidden' });
  const shared = await (await context.request.get(base + '/api/items?collection=' + b.id)).json();
  assert.equal(shared.total, 1); assert.equal(db.prepare('SELECT count(DISTINCT file_key) n FROM items WHERE kind=\'image\'').get().n, 3);
  await page.screenshot({ path: resolve('artifacts/v03-gallery-desktop.png'), fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: '关闭窗口' }).click();
  await page.getByRole('button', { name: '选择内容', exact: true }).click();
  await page.getByLabel('选择当前页全部内容').check();
  await page.getByRole('button', { name: '移动 / 收藏' }).click();
  await page.getByLabel('批量收藏状态').selectOption('yes');
  await page.getByRole('button', { name: '确认整理' }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  records = await (await context.request.get(base + '/api/items?collection=' + a.id)).json();
  assert.ok(records.items.every(i => i.favorite));
  console.log('PASS: cross-library reuse shares one file; batch favorites affect selected entries');
  await page.getByLabel('选择 上传后直接整理', { exact: true }).check();
  await page.getByRole('button', { name: '移动 / 收藏' }).click();
  await page.getByLabel('移动到知识库', { exact: true }).check();
  await page.getByLabel('整理目标知识库').selectOption(b.id);
  await page.getByRole('button', { name: '确认整理' }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  const moved = await (await context.request.get(base + '/api/items?collection=' + b.id)).json();
  assert.ok(moved.items.some(i => i.title === '上传后直接整理'));
  console.log('PASS: batch move changes the selected entry library');
  await page.getByRole('button', { name: '退出选择', exact: true }).click();
  await page.getByRole('button', { name: '打开 研究素材3.png' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('dialog').evaluate(el => { el.scrollTop = 0; });
  await page.screenshot({ path: resolve('artifacts/v03-gallery-mobile.png'), fullPage: true, animations: 'disabled' });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  assert.deepEqual(errors, []);
  console.log('PASS: mobile gallery fits viewport; no page errors');
} catch (e) {
  await page.screenshot({ path: resolve('artifacts/v03-ui-failure.png'), fullPage: true }); throw e;
} finally { await browser.close(); await new Promise(r => server.close(r)); db.close(); }
