import {chromium} from 'playwright';
import {mkdtemp} from 'node:fs/promises';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {createApp} from '../server/app.js';
const dir=await mkdtemp(resolve('artifacts/preview-v093-')),runtime=createApp({dataDir:dir,staticDir:resolve(process.env.UI_DIST||'dist')}),server=runtime.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1500,height:1050}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const post=async(path,data)=>{const r=await context.request.post(base+path,{data});assert.ok(r.ok(),await r.text());return r.json()};
try{
 await post('/api/auth/setup',{password:'0933'});const a=await post('/api/collections',{name:'插画'}),b=await post('/api/collections',{name:'资料'});await post('/api/items',{title:'资料专属笔记',collection_id:b.id,tags:['资料独有']});
 const images=[];for(let i=0;i<3;i++){const buffer=await sharp({create:{width:1200,height:800,channels:3,background:['#988abf','#769aac','#b19a7d'][i]}}).png().toBuffer();const r=await context.request.post(base+'/api/assets',{multipart:{file:{name:'page.png',mimeType:'image/png',buffer},collection_id:a.id,title:'插画 '+(i+1),tags:JSON.stringify(['插画独有']),content:'作者：[测试作者](https://www.pixiv.net/users/1)\n\n**手绘记录**\n\n原文件：https://i.pximg.net/img-original/test.png\n\n来源链接：https://www.pixiv.net/artworks/12345',source_url:'https://www.pixiv.net/artworks/12345',group_key:'pixiv:art:12345',group_index:String(i),group_title:'插画合集'}});assert.ok(r.ok());images.push(await r.json())}
 const note=await post('/api/items',{title:'读图笔记',collection_id:a.id,content:images.map((i,index)=>`![分镜 ${index+1}](${i.url})`).join('\n\n'),tags:['笔记独有']});
 const rows=runtime.db.prepare('SELECT * FROM items WHERE group_key=? ORDER BY group_index').all('note:'+note.id);assert.equal(rows.length,3);assert.equal(new Set(runtime.db.prepare("SELECT file_key FROM items WHERE kind='image'").all().map(i=>i.file_key)).size,3);assert.ok(rows.every(r=>r.collection_id===a.id));
 await context.request.patch(base+'/api/preferences',{data:{default_collection_id:a.id}});await page.goto(base);await page.getByRole('button',{name:'打开 读图笔记 · 配图',exact:true}).waitFor();
 await page.getByRole('button',{name:'打开 插画合集',exact:true}).click();let dialog=page.getByRole('dialog',{name:'图片详情',exact:true});await dialog.locator('.gallery-strip button').first().waitFor();assert.equal(await dialog.locator('.source-info a').count(),1);assert.equal(await dialog.locator('.media-description strong').innerText(),'手绘记录');assert.ok(!(await dialog.locator('.media-description').innerText()).includes('原文件'));assert.equal(await dialog.locator('.media-description a').getAttribute('href'),'https://www.pixiv.net/users/1');
 await dialog.locator('.gallery-strip button').nth(1).click();await dialog.getByText('第 2 / 3 张',{exact:true}).waitFor();await page.keyboard.press('d');await dialog.getByText('第 3 / 3 张',{exact:true}).waitFor();await page.keyboard.press('ArrowLeft');await dialog.getByText('第 2 / 3 张',{exact:true}).waitFor();await page.keyboard.press('a');await dialog.getByText('第 1 / 3 张',{exact:true}).waitFor();
 await dialog.getByRole('button',{name:'全屏查看图片',exact:true}).hover();await page.mouse.wheel(0,140);await dialog.getByText('第 2 / 3 张',{exact:true}).waitFor();
 await dialog.getByRole('button',{name:'全屏查看图片',exact:true}).click();const zoom=page.getByRole('dialog',{name:'展开图片',exact:true});await zoom.locator('.zoom-surface').hover();await page.mouse.wheel(0,-280);await page.waitForFunction(()=>document.querySelector('.zoom-tools output').textContent!=='100%');assert.ok(parseInt(await zoom.locator('output').innerText())>100);assert.equal(await dialog.locator('.gallery-position').innerText(),'第 2 / 3 张');await zoom.getByRole('button',{name:'重置缩放'}).click();assert.equal(await zoom.locator('output').innerText(),'100%');await page.keyboard.press('Escape');await zoom.waitFor({state:'hidden'});
 await dialog.locator('#item-title').fill('输入 a/d 不翻页');await page.keyboard.press('d');assert.equal(await dialog.locator('.gallery-position').innerText(),'第 2 / 3 张');await dialog.locator('#item-title').fill('插画 2');
 await page.evaluate(()=>{document.documentElement.dataset.theme='dark';document.documentElement.dataset.style='minimal';document.documentElement.dataset.palette='slate'});
 const colors=await dialog.locator('select option').first().evaluate(el=>({fg:getComputedStyle(el).color,bg:getComputedStyle(el).backgroundColor}));assert.notEqual(colors.fg,colors.bg);assert.notEqual(colors.bg,'rgb(255, 255, 255)');
 await dialog.getByRole('combobox',{name:'所属知识库'}).selectOption(b.id);await dialog.locator('.tag-suggestions').getByRole('button',{name:/资料独有/}).waitFor();assert.ok(!(await dialog.locator('.tag-suggestions').innerText()).includes('笔记独有'));await dialog.getByRole('combobox',{name:'所属知识库'}).selectOption(a.id);
 await page.waitForTimeout(350);console.log('preview controls',await dialog.locator('button').first().evaluate(el=>({fg:getComputedStyle(el).color,bg:getComputedStyle(el).backgroundColor})));await page.screenshot({path:resolve('artifacts/v093-preview-dark.png')});await dialog.getByRole('button',{name:'关闭窗口',exact:true}).click();
 await page.getByRole('button',{name:'打开 读图笔记',exact:true}).click();const noteDialog=page.getByRole('dialog',{name:'图文笔记',exact:true});await noteDialog.locator('.markdown-preview img').first().click();const gallery=page.getByRole('dialog',{name:'笔记配图',exact:true});await gallery.getByText('第 1 / 3 张',{exact:true}).waitFor();await page.keyboard.press('d');await gallery.getByText('第 2 / 3 张',{exact:true}).waitFor();await gallery.getByRole('button',{name:'展开笔记配图'}).hover();await page.mouse.wheel(0,140);await gallery.getByText('第 3 / 3 张',{exact:true}).waitFor();await gallery.getByRole('button',{name:'展开笔记配图'}).click();await zoom.locator('.zoom-surface').hover();await page.mouse.wheel(0,-280);await page.waitForFunction(()=>document.querySelector('.zoom-tools output').textContent!=='100%');await page.keyboard.press('Escape');await zoom.waitFor({state:'hidden'});await gallery.getByText('第 3 / 3 张',{exact:true}).waitFor();await gallery.getByRole('button',{name:'关闭窗口',exact:true}).click();await noteDialog.getByRole('button',{name:'关闭窗口',exact:true}).click();
 await page.getByRole('button',{name:'打开 读图笔记 · 配图',exact:true}).click();dialog=page.getByRole('dialog',{name:'图片详情',exact:true});await dialog.getByRole('combobox',{name:'所属知识库'}).selectOption(b.id);await dialog.getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('status').filter({hasText:'已移动整组 3 张图片及所属笔记'}).waitFor();assert.equal(runtime.db.prepare('SELECT collection_id FROM items WHERE id=?').get(note.id).collection_id,b.id);assert.ok(runtime.db.prepare('SELECT collection_id FROM items WHERE group_key=?').all('note:'+note.id).every(r=>r.collection_id===b.id));assert.ok(runtime.db.prepare('SELECT collection_id FROM items WHERE group_key=?').all('pixiv:art:12345').every(r=>r.collection_id===a.id));
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:resolve('artifacts/v093-preview-mobile.png')});await dialog.getByRole('button',{name:'关闭窗口',exact:true}).click();await page.setViewportSize({width:1500,height:1050});await page.getByRole('button',{name:'选择内容',exact:true}).click();const check=page.locator('.card-select input').first();await check.check();assert.ok(await check.isChecked());await page.waitForTimeout(250);const selectorColors=await page.locator('.card-select').first().evaluate(el=>({bg:getComputedStyle(el).backgroundColor,fg:getComputedStyle(el).color,surface:getComputedStyle(document.documentElement).getPropertyValue('--surface').trim()}));assert.notEqual(selectorColors.bg,'rgba(39, 59, 33, 0.937)');assert.notEqual(selectorColors.bg,selectorColors.fg);await page.screenshot({path:resolve('artifacts/v093-selection-dark.png')});assert.deepEqual(errors,[]);console.log('PASS note groups/shared originals, thumbnails, A/D/arrows/wheel, expanded zoom, scoped tags, concise Markdown, group+note move and dark/mobile layout');
}finally{await browser.close();await runtime.imports.stop();await runtime.backups.stop();await runtime.webhooks.stop();await new Promise(r=>server.close(r));runtime.db.close()}
