import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtemp,writeFile} from 'node:fs/promises';import {resolve,join} from 'node:path';import sharp from 'sharp';import {createApp} from '../server/app.js';import {openDatabase} from '../server/db.js';

test('reading progress is scoped, bounded, conflict-safe and restored without changing content',async t=>{
 const dir=await mkdtemp(resolve('artifacts/reading-progress-'));let runtime,server,base,cookie;
 async function start(){runtime=createApp({dataDir:dir});server=runtime.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port}
 async function stop(){await runtime.trash.stop();await runtime.imports.stop();await runtime.backups.stop();await runtime.webhooks.stop();await new Promise(r=>server.close(r));runtime.db.close()}
 await start();t.after(stop);const req=(path,method='GET',data,headers={})=>fetch(base+path,{method,headers:{Cookie:cookie||'',...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});const json=async(...args)=>{const r=await req(...args);assert.ok(r.ok,await r.clone().text());return r.json()};const setup=await req('/api/auth/setup','POST',{password:'0920'});cookie=setup.headers.get('set-cookie').split(';')[0];
 const a=await json('/api/collections','POST',{name:'甲'}),b=await json('/api/collections','POST',{name:'乙'});
 const pixels=await sharp({create:{width:24,height:20,channels:3,background:'#789abc'}}).png().toBuffer(),form=new FormData();form.set('file',new Blob([pixels]),'test.png');form.set('collection_id',a.id);const uploaded=await fetch(base+'/api/assets',{method:'POST',headers:{Cookie:cookie},body:form});const first=await uploaded.json();
 const original=runtime.db.prepare('SELECT * FROM items WHERE id=?').get(first.id),columns=Object.keys(original),insert=runtime.db.prepare(`INSERT INTO items(${columns.join(',')}) VALUES(${columns.map(()=>'?').join(',')})`),ids=[];
 for(let i=0;i<25;i++){const row={...original,id:randomUUID(),title:'页 '+i,group_key:i<3?'comic:1':null,group_title:i<3?'画册':null,group_index:i,group_order:i};insert.run(...columns.map(c=>row[c]));ids.push(row.id)}
 const contentBefore=runtime.db.prepare('SELECT * FROM items ORDER BY id').all(),events=runtime.db.prepare('SELECT * FROM events').all();
 const read=()=>json('/api/reading-progress?collection='+a.id);const body=(state,id)=>({collection_id:a.id,item_id:id,version:state.version,epoch:state.epoch,request_id:randomUUID()});let state=await read();assert.equal(state.version,0);
 const request=body(state,ids[1]);state=await json('/api/reading-progress','POST',request);assert.equal(state.entries[0].position,2);assert.equal(state.entries[0].total,3);assert.equal((await json('/api/reading-progress','POST',request)).replayed,true);
 assert.equal((await req('/api/reading-progress','POST',{...request,request_id:randomUUID(),item_id:ids[2]})).status,409);
 assert.equal((await req('/api/reading-progress','POST',{...body(state,ids[2]),collection_id:b.id,version:0})).status,409);
 assert.equal((await json('/api/reading-progress?collection='+b.id)).entries.length,0);
 state=await json('/api/reading-progress','POST',body(state,ids[2]));assert.equal(state.entries.length,1);assert.equal(state.entries[0].item_id,ids[2]);
 assert.deepEqual(runtime.db.prepare('SELECT * FROM items ORDER BY id').all(),contentBefore);assert.deepEqual(runtime.db.prepare('SELECT * FROM events').all(),events);
 runtime.db.prepare('UPDATE items SET group_order=-1 WHERE id=?').run(ids[2]);assert.equal((await read()).entries[0].position,1);
 runtime.db.prepare('UPDATE items SET deleted_at=? WHERE id=?').run(new Date().toISOString(),ids[2]);assert.equal((await read()).entries.length,0);runtime.db.prepare('UPDATE items SET deleted_at=NULL WHERE id=?').run(ids[2]);assert.equal((await read()).entries.length,1);
 runtime.db.prepare('UPDATE items SET collection_id=? WHERE id=?').run(b.id,ids[2]);assert.equal((await read()).entries.length,0);runtime.db.prepare('UPDATE items SET collection_id=? WHERE id=?').run(a.id,ids[2]);
 for(const id of ids.slice(3))state=await json('/api/reading-progress','POST',body(state,id));assert.equal(state.entries.length,20);
 const reader=await json('/api/tokens','POST',{name:'只读',scope:'read'});assert.equal((await req('/api/reading-progress','POST',body(state,ids[0]),{Authorization:'Bearer '+reader.token})).status,403);
 await stop();await start();assert.deepEqual(await read(),state);
 const zip=join(dir,'backup.zip');await writeFile(zip,Buffer.from(await(await req('/api/export?mode=backup')).arrayBuffer()));const restored=createApp({dataDir:join(dir,'restore')});
 try{const p=await restored.backups.preview(zip);await restored.backups.restore(p.id);assert.deepEqual(restored.db.prepare('SELECT * FROM reading_progress').all(),runtime.db.prepare('SELECT * FROM reading_progress').all());assert.notEqual(restored.db.prepare("SELECT value FROM settings WHERE key='reading_epoch'").get().value,state.epoch)}finally{await restored.trash.stop();await restored.imports.stop();await restored.backups.stop();await restored.webhooks.stop();restored.db.close()}
 const clear={collection_id:a.id,version:state.version,epoch:state.epoch,request_id:randomUUID()};state=await json('/api/reading-progress','DELETE',clear);assert.equal(state.entries.length,0);assert.equal((await json('/api/reading-progress','DELETE',clear)).replayed,true);assert.equal((await req('/api/reading-progress','POST',request)).status,409);
 const changed=body(state,ids[0]);changed.epoch='older-backup';assert.equal((await req('/api/reading-progress','POST',changed)).status,409);
});

test('schema 11 upgrades reading history additively and remains idempotent',async()=>{const dir=await mkdtemp(resolve('artifacts/reading-migration-'));let db=openDatabase(dir);db.exec("DROP TABLE reading_progress; DELETE FROM settings WHERE key='reading_epoch'; PRAGMA user_version=11");db.prepare("INSERT INTO items(id,kind,title,content,created_at,updated_at) VALUES(?,'note','原笔记','原文','2026-09-13','2026-09-13')").run(randomUUID());const before=db.prepare('SELECT * FROM items').all();db.close();db=openDatabase(dir);assert.equal(db.prepare('PRAGMA user_version').get().user_version,12);assert.deepEqual(db.prepare('SELECT * FROM items').all(),before);const epoch=db.prepare("SELECT value FROM settings WHERE key='reading_epoch'").get().value;db.close();db=openDatabase(dir);assert.equal(db.prepare("SELECT value FROM settings WHERE key='reading_epoch'").get().value,epoch);db.close()});
