import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,writeFile,copyFile,readFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import sharp from 'sharp';
import {createApp} from '../server/app.js';
const dir=await mkdtemp(resolve('artifacts/tasks-ui-'));let importAttempts=0,releaseExport,seenExport,exportGate;
const runtime=createApp({dataDir:dir,staticDir:resolve(process.env.UI_DIST||'dist'),importOptions:{downloader:async({dir,progress})=>{importAttempts++;progress('测试下载');if(importAttempts===1)throw Object.assign(Error('临时采集失败'),{status:422});const path=join(dir,'sample.mp4');await copyFile(resolve('tests/fixtures/sample.mp4'),path);return{path,originalname:'sample.mp4',title:'任务视频',author:'测试作者'};}}}),server=createServer(async(req,res)=>{if(exportGate&&/^\/api\/export-jobs\/[^/]+\/file$/.test(req.url)){seenExport();await exportGate;}runtime.app(req,res)}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1366,height:768},acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const post=async(path,data)=>{const r=await context.request.post(base+path,{data});assert.ok(r.ok(),await r.text());return r.json();};
const center=page.getByRole('dialog',{name:'任务中心',exact:true}),row=name=>center.locator('.task-row').filter({hasText:name});
const openCenter=async()=>{await page.getByRole('button',{name:'任务中心',exact:true}).click();await center.waitFor();};
const close=async dialog=>{await dialog.getByRole('button',{name:'关闭窗口',exact:true}).click();await dialog.waitFor({state:'hidden'});};
try{
  await post('/api/auth/setup',{password:'0923'});const a=await post('/api/collections',{name:'上传目标'}),b=await post('/api/collections',{name:'另一个库'});await context.request.patch(base+'/api/preferences',{data:{default_collection_id:a.id}});
  const files=[];for(let i=0;i<3;i++){const path=join(dir,['一.png','二.png','三.png'][i]);await writeFile(path,await sharp({create:{width:240,height:160,channels:3,background:['#709bb9','#bc89a7','#90a365'][i]}}).png().toBuffer());files.push(path);}
  let release,firstSeen,first=true,failSecond=true,thirdRequests=0;const gate=new Promise(r=>release=r),arrived=new Promise(r=>firstSeen=r);
  await page.route('**/api/assets',async route=>{const body=route.request().postDataBuffer().toString();if(body.includes('一.png')&&first){first=false;firstSeen();await gate;}if(body.includes('三.png'))thirdRequests++;if(body.includes('二.png')&&failSecond){failSecond=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'临时上传失败'})});}else await route.continue();});
  await page.goto(base);await page.getByRole('button',{name:'上传图片',exact:true}).click();const upload=page.getByRole('dialog',{name:'批量上传图片',exact:true});await upload.locator('input[type=file]').setInputFiles(files);await upload.getByLabel('批量上传标签').fill('队列标签');await upload.getByLabel('批量上传标签').press('Enter');await upload.getByRole('button',{name:'开始上传',exact:true}).click();await arrived;await close(upload);await openCenter();
  await row('三.png').getByRole('button',{name:'取消',exact:true}).click();await row('三.png').getByText('已取消，尚未开始',{exact:true}).waitFor();assert.equal(thirdRequests,0);
  await center.getByLabel('任务知识库').selectOption(b.id);assert.equal(await center.locator('.task-row').count(),0);await center.getByLabel('任务知识库').selectOption(a.id);assert.equal(await center.locator('.task-row').count(),3);await close(center);release();
  await page.getByRole('button',{name:'打开 一.png',exact:true}).waitFor();await openCenter();await row('二.png').getByText('临时上传失败',{exact:true}).waitFor();await row('二.png').getByRole('button',{name:'重试',exact:true}).click();await row('二.png').getByText('已入库',{exact:true}).waitFor();assert.equal(thirdRequests,0);
  await row('三.png').getByRole('button',{name:'重试',exact:true}).click();await row('三.png').getByText('已入库',{exact:true}).waitFor();assert.equal(thirdRequests,1);await page.unrouteAll();
  const images=runtime.db.prepare("SELECT tags,collection_id FROM items WHERE kind='image'").all();assert.equal(images.length,3);assert.ok(images.every(r=>r.collection_id===a.id&&JSON.parse(r.tags).includes('队列标签')));
  await row('二.png').getByRole('button',{name:'打开内容',exact:true}).click();await center.waitFor({state:'hidden'});const detail=page.getByRole('dialog',{name:'图片详情',exact:true});assert.equal(await detail.getByLabel('标题',{exact:true}).inputValue(),'二.png');await close(detail);
  // Export survives closing its settings dialog; completion means handed to browser.
  exportGate=new Promise(r=>releaseExport=r);const exportArrived=new Promise(r=>seenExport=r);await page.getByRole('button',{name:'导出',exact:true}).click();const exporting=page.getByRole('dialog',{name:'导出知识库',exact:true});await exporting.getByRole('button',{name:/JSON 元数据/}).click();const download=page.waitForEvent('download');await exporting.getByRole('button',{name:'下载导出文件',exact:true}).click();await exportArrived;await close(exporting);await openCenter();await row('JSON 元数据').getByText('等待浏览器接收下载',{exact:true}).waitFor();releaseExport();const file=await download;assert.equal(file.suggestedFilename(),'znote-metadata.json');assert.ok((await readFile(await file.path(),'utf8')).includes('队列标签'));await row('JSON 元数据').getByText('服务器已传送完成；保存结果请查看浏览器下载列表',{exact:true}).waitFor();await page.unrouteAll();await close(center);
  // Server retry keeps original target and tags, even after the creation dialog closed.
  const job=await post('/api/imports',{url:'https://www.bilibili.com/video/BV1xx411c7mD',collection_id:a.id,tags:['采集标签']});await openCenter();await center.getByRole('button',{name:'刷新任务',exact:true}).click();await center.locator('[data-task-id="import:'+job.id+'"]').getByRole('button',{name:'重试',exact:true}).waitFor();await center.locator('[data-task-id="import:'+job.id+'"]').getByRole('button',{name:'重试',exact:true}).click();await row('任务视频').getByRole('button',{name:'打开内容',exact:true}).waitFor();const video=runtime.db.prepare("SELECT * FROM items WHERE kind='video'").get();assert.equal(video.collection_id,a.id);assert.ok(JSON.parse(video.tags).includes('采集标签'));assert.ok(JSON.parse(video.tags).includes('测试作者'));
  await center.getByRole('button',{name:'备份设置',exact:true}).click();const settings=page.getByRole('dialog',{name:'设置与连接',exact:true});await settings.waitFor();await settings.getByRole('button',{name:'立即备份',exact:true}).click();await close(settings);await openCenter();await row('完整备份').getByRole('link',{name:'下载备份',exact:true}).first().waitFor();assert.ok((await runtime.backups.status()).backups.length>=1);
  await page.evaluate(()=>{document.documentElement.dataset.theme='dark';document.documentElement.dataset.style='minimal';document.documentElement.dataset.palette='slate'});await page.waitForTimeout(300);await page.screenshot({path:resolve('artifacts/v0924-tasks-desktop.png')});await page.setViewportSize({width:390,height:844});await page.screenshot({path:resolve('artifacts/v0924-tasks-mobile.png')});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await center.getByRole('button',{name:'清除本地已结束记录',exact:true}).click();assert.equal(await center.locator('.task-row[data-task-id^="import:"]').count(),2);assert.equal(runtime.db.prepare('SELECT count(*) n FROM items').get().n,4);assert.deepEqual(errors,[]);
  await close(center);await page.setViewportSize({width:1366,height:768});await page.getByRole('button',{name:'上传图片',exact:true}).click();await upload.locator('input[type=file]').setInputFiles(Array(51).fill(files[0]));assert.equal(await upload.locator('.upload-row').count(),50);await upload.getByRole('button',{name:'下一页文件',exact:true}).click();assert.equal(await upload.locator('.upload-row').count(),1);await close(upload);
  console.log('PASS Edge: shared sequential uploads continue after dialog close, queued cancel/retry, original library/tags, export download after close, import retry and author metadata, backup result, local clear without deleting content, desktop/mobile task center');
}finally{releaseExport?.();await page.unrouteAll({behavior:'ignoreErrors'});await browser.close();await runtime.trash.stop();await runtime.imports.stop();await runtime.backups.stop();await runtime.webhooks.stop();await new Promise(r=>server.close(r));runtime.db.close();}
