import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { resolve } from 'node:path';
import sharp from 'sharp';
import { createApp } from '../server/app.js';
const dir = await mkdtemp(resolve('artifacts/undo-ui-')), runtime = createApp({ dataDir: dir, staticDir: resolve(process.env.UI_DIST || 'dist') });
const server = runtime.app.listen(0, '127.0.0.1'); await new Promise(r => server.once('listening', r)); const base = 'http://127.0.0.1:' + server.address().port;
const browser = await chromium.launch({ channel: 'msedge', headless: true }), context = await browser.newContext({ viewport: { width: 1440, height: 1000 } }), page = await context.newPage(), errors = [];
page.on('pageerror', e => errors.push(e.message));
const post = async (path, data) => { const r = await context.request.post(base + path, { data }); assert.ok(r.ok(), await r.text()); return r.json(); };
try {
  await post('/api/auth/setup', { password: '0915' });
  const library = await post('/api/collections', { name: '撤销测试库' });
  const buffer = await sharp({ create: { width: 120, height: 80, channels: 3, background: '#789abc' } }).png().toBuffer();
  const upload = await context.request.post(base + '/api/assets', { multipart: { title: '原始图片', collection_id: library.id, file: { name: '原始图片.png', mimeType: 'image/png', buffer } } }); assert.ok(upload.ok()); const image = await upload.json();
  await context.request.patch(base + '/api/preferences', { data: { default_collection_id: library.id } });
  await page.goto(base); await page.getByRole('button', { name: '打开 原始图片', exact: true }).click();
  const detail = page.getByRole('dialog', { name: '图片详情', exact: true });
  await detail.getByRole('button', { name: '移至回收站', exact: true }).click();
  await detail.waitFor({ state: 'hidden' });
  await page.locator('.undo-notice').getByRole('button', { name: '撤销', exact: true }).click();
  await page.getByRole('button', { name: '打开 原始图片', exact: true }).waitFor();
  assert.equal(runtime.db.prepare('SELECT deleted_at FROM items WHERE id=?').get(image.id).deleted_at, null);
  await page.getByRole('button', { name: '收藏 原始图片', exact: true }).click();
  await page.locator('.undo-notice').waitFor();
  await page.reload(); await page.getByRole('button', { name: '最近操作', exact: true }).click();
  const history = page.getByRole('dialog', { name: '最近操作', exact: true });
  await history.locator('.undo-row').filter({ hasText: '编辑内容' }).getByRole('button', { name: '撤销', exact: true }).click();
  assert.equal(runtime.db.prepare('SELECT favorite FROM items WHERE id=?').get(image.id).favorite, 0);
  await history.getByRole('button', { name: '关闭窗口', exact: true }).click();
  await page.getByRole('button', { name: '选择内容', exact: true }).click();
  await page.locator('.card-main').click();
  await page.getByRole('button', { name: '批量标签', exact: true }).click();
  const tags = page.getByRole('dialog', { name: '批量标签 · 1 项内容', exact: true });
  await tags.getByRole('textbox', { name: '批量编辑标签', exact: true }).fill('作者'); await tags.getByRole('textbox', { name: '批量编辑标签', exact: true }).press('Enter');
  await tags.getByRole('button', { name: '应用标签', exact: true }).click(); await tags.waitFor({ state: 'hidden' });
  assert.equal(runtime.db.prepare('SELECT tags FROM items WHERE id=?').get(image.id).tags, '["作者"]');
  await page.locator('.undo-notice').getByRole('button', { name: '撤销', exact: true }).click();
  assert.equal(runtime.db.prepare('SELECT tags FROM items WHERE id=?').get(image.id).tags, '[]');
  // A concurrent change produces an honest conflict and retains newer data.
  await page.getByRole('button', { name: '收藏 原始图片', exact: true }).click();
  const current = runtime.db.prepare('SELECT version FROM items WHERE id=?').get(image.id);
  await context.request.patch(base + '/api/items/' + image.id, { data: { version: current.version, favorite: false } });
  await page.locator('.undo-notice').getByRole('button', { name: '撤销', exact: true }).click();
  await page.locator('.undo-notice [role=alert]').waitFor();
  assert.equal(runtime.db.prepare('SELECT favorite FROM items WHERE id=?').get(image.id).favorite, 0);
  await page.getByRole('button', { name: '最近操作', exact: true }).click();
  await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; document.documentElement.dataset.palette = 'slate'; });
  await page.waitForTimeout(250); await page.screenshot({ path: resolve('artifacts/v0915-undo-desktop.png') });
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: resolve('artifacts/v0915-undo-mobile.png') });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); assert.deepEqual(errors, []);
  console.log('PASS Edge: delete undo, history after reload, favorite and batch tags undo, conflict preservation, dark desktop/mobile');
} finally { await browser.close(); await runtime.trash.stop(); await runtime.imports.stop(); await runtime.backups.stop(); await runtime.webhooks.stop(); await new Promise(r => server.close(r)); runtime.db.close(); }
